game:
  min-players: 1
  max-players: 25
  day-duration: 180          # 3 min in seconds
  discussion-duration: 120   # 2 min
  voting-duration: 15        # 15 sec
  parasite-swap-cooldown: 120 # 2 min in seconds
  lobby-countdown: 30

locations:
  lobby: null
  arena: null

# Sign stacks: 2 stacks of 16
signs-per-stack: 16
sign-stacks: 2